# Generated by Django 5.2.8 on 2025-11-22 20:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("candidate", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="acceptedcandidate",
            name="resume_file",
            field=models.CharField(max_length=300),
        ),
    ]
