# Generated by Django 5.2.8 on 2025-11-22 20:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("upload", "0002_resume_email_resume_name_resume_parsed_text"),
    ]

    operations = [
        migrations.CreateModel(
            name="AcceptedCandidate",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=200)),
                ("email", models.EmailField(max_length=254)),
                ("resume_file", models.CharField(max_length=500)),
                ("score", models.FloatField()),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
